apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-design-system
  labels:
    app: automation-design-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: automation-design-system
  template:
    metadata:
      labels:
        app: automation-design-system
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: automation-app
        image: IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  // Assuming the app listens on port 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: automation-design-system
  labels:
    app: automation-design-system
spec:
  type: LoadBalancer
  selector:
    app: automation-design-system
  ports:
  - port: 80
    targetPort: 8080
